# Generated by Django 5.1 on 2024-09-30 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0004_alter_estudiante_numid_alter_estudiante_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.IntegerField(default=None)),
                ('estado', models.CharField(choices=[('MOR', 'Moroso'), ('NOM', 'No Moroso')], default='NOM', max_length=3)),
                ('estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
        ),
    ]
