# Generated by Django 2.2.4 on 2024-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_auto_20240930_1611'),
        ('cuenta', '0002_auto_20240930_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='pagos',
            field=models.ManyToManyField(related_name='pagos', to='pago.Pago'),
        ),
    ]
