# Generated by Django 5.1 on 2024-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numId', models.IntegerField(max_length=10)),
                ('telefono', models.IntegerField(max_length=10)),
                ('colegio', models.CharField(max_length=100)),
                ('carnet', models.IntegerField(max_length=10)),
                ('grado', models.IntegerField(max_length=10)),
                ('curso', models.IntegerField(max_length=10)),
            ],
        ),
    ]
