# Generated by Django 5.1 on 2024-09-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='carnet',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='numId',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='telefono',
        ),
    ]
