# Generated by Django 5.1 on 2024-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_remove_estudiante_carnet_remove_estudiante_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carnet',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numId',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.IntegerField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='colegio',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
