# Generated by Django 5.1 on 2024-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_estudiante_carnet_estudiante_curso_estudiante_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='numId',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.IntegerField(default=None),
        ),
    ]
