# Generated by Django 5.1.3 on 2024-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0006_alter_estudiante_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='emailPadreFamilia',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
