# Generated by Django 5.1 on 2024-09-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=None)),
                ('causacion', models.CharField(max_length=80)),
                ('fechaLimite', models.DateField()),
                ('estado', models.CharField(choices=[('PAG', 'Pagado'), ('NOP', 'No Pagado')], default='NOP', max_length=3)),
                ('mes', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='01', max_length=2)),
            ],
        ),
    ]
